-- Extended fields for rescue case to support Flutter app
ALTER TABLE cases ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS location_label VARCHAR(255);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS species VARCHAR(100);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS injury_type VARCHAR(100);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS probable_condition TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS first_aid_steps TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS estimated_cost_inr INTEGER;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS donated_amount_inr INTEGER DEFAULT 0;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS notes TEXT;
